load("//devtools/python/blaze:pytype.bzl", "pytype_strict_library")

pytype_strict_library(
    name = "mae_lsm_base_mask_ratio_sweep",
    srcs = ["mae_lsm_base_mask_ratio_sweep.py"],
    deps = [
        "//experimental/largesensormodels/scenic/models/lsm_vit_utils:model_constants",
        "//third_party/py/ml_collections",
    ],
)

pytype_strict_library(
    name = "mae_lsm_base_mask_strat_sweep",
    srcs = ["mae_lsm_base_mask_strat_sweep.py"],
    deps = [
        "//experimental/largesensormodels/scenic/models/lsm_vit_utils:model_constants",
        "//third_party/py/ml_collections",
    ],
)

pytype_strict_library(
    name = "mae_lsm_base_patch_size_sweep",
    srcs = ["mae_lsm_base_patch_size_sweep.py"],
    deps = [
        "//experimental/largesensormodels/scenic/models/lsm_vit_utils:model_constants",
        "//third_party/py/ml_collections",
    ],
)
